apiVersion: config.kio.kasten.io/v1alpha1
kind: PolicyPreset
metadata:
  name: bronze-policy-preset
  namespace: kasten-io
spec:
  comment: Policy preset for bronze backup
  backup:
    frequency: '@weekly'
    profile:
      name: "profile-gcs-{{ bucket_namegcp }}"
      namespace: kasten-io    
    subFrequency:
      weekdays: [6]
    backupWindow:
        start:
          hour: 22
          minute: 30
        end:
          hour: 7
          minute: 0          
    retention:
      weekly: 4      
      monthly: 6
  export:
    frequency: '@weekly'
    exportData:
      enabled: true
    profile:
      name: "profile-gcs-{{ bucket_namegcp }}"
      namespace: kasten-io
    retention:
      weekly: 4     
      monthly: 6
